{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "dc118a05",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\h5py\\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\n",
      "  from ._conv import register_converters as _register_converters\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "import time\n",
    "import math\n",
    "import Cifar10_data as Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ebe80634",
   "metadata": {},
   "outputs": [],
   "source": [
    "max_steps=4000\n",
    "batch_size=100\n",
    "num_examples_for_eval=10000\n",
    "data_dir=\"cifar-10-batches-bin\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "8ef6c977",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From C:\\Users\\TEMP.DESKTOP-TS8HMUH.008\\Cifar10_data.py:49: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.\n",
      "WARNING:tensorflow:From E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\input.py:276: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.\n",
      "WARNING:tensorflow:From E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\input.py:188: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.\n",
      "WARNING:tensorflow:From E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\input.py:197: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "To construct input pipelines, use the `tf.data` module.\n",
      "WARNING:tensorflow:From E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\input.py:197: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "To construct input pipelines, use the `tf.data` module.\n",
      "WARNING:tensorflow:From C:\\Users\\TEMP.DESKTOP-TS8HMUH.008\\Cifar10_data.py:27: FixedLengthRecordReader.__init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.FixedLengthRecordDataset`.\n",
      "Filling queue with 4000 CIFAR images before starting to train.    This will take a few minutes.\n",
      "WARNING:tensorflow:From C:\\Users\\TEMP.DESKTOP-TS8HMUH.008\\Cifar10_data.py:78: shuffle_batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.shuffle(min_after_dequeue).batch(batch_size)`.\n",
      "WARNING:tensorflow:From C:\\Users\\TEMP.DESKTOP-TS8HMUH.008\\Cifar10_data.py:96: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).\n",
      "WARNING:tensorflow:From <ipython-input-4-adb98b31c9ee>:71: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "To construct input pipelines, use the `tf.data` module.\n",
      "step 0,loss=4.68(36.1 examples/sec;2.773 sec/batch)\n",
      "step 100,loss=2.12(279.3 examples/sec;0.358 sec/batch)\n",
      "step 200,loss=1.72(307.6 examples/sec;0.325 sec/batch)\n",
      "step 300,loss=1.55(265.3 examples/sec;0.377 sec/batch)\n",
      "step 400,loss=1.77(275.5 examples/sec;0.363 sec/batch)\n",
      "step 500,loss=1.35(292.3 examples/sec;0.342 sec/batch)\n",
      "step 600,loss=1.41(231.6 examples/sec;0.432 sec/batch)\n",
      "step 700,loss=1.49(271.7 examples/sec;0.368 sec/batch)\n",
      "step 800,loss=1.58(248.8 examples/sec;0.402 sec/batch)\n",
      "step 900,loss=1.28(271.7 examples/sec;0.368 sec/batch)\n",
      "step 1000,loss=1.35(300.2 examples/sec;0.333 sec/batch)\n",
      "step 1100,loss=1.42(297.5 examples/sec;0.336 sec/batch)\n",
      "step 1200,loss=1.32(282.4 examples/sec;0.354 sec/batch)\n",
      "step 1300,loss=1.19(274.0 examples/sec;0.365 sec/batch)\n",
      "step 1400,loss=1.22(277.0 examples/sec;0.361 sec/batch)\n",
      "step 1500,loss=1.30(296.7 examples/sec;0.337 sec/batch)\n",
      "step 1600,loss=1.41(284.0 examples/sec;0.352 sec/batch)\n",
      "step 1700,loss=1.11(271.0 examples/sec;0.369 sec/batch)\n",
      "step 1800,loss=1.21(268.8 examples/sec;0.372 sec/batch)\n",
      "step 1900,loss=1.15(231.6 examples/sec;0.432 sec/batch)\n",
      "step 2000,loss=1.17(215.6 examples/sec;0.464 sec/batch)\n",
      "step 2100,loss=1.16(263.2 examples/sec;0.380 sec/batch)\n",
      "step 2200,loss=0.93(234.3 examples/sec;0.427 sec/batch)\n",
      "step 2300,loss=1.13(245.2 examples/sec;0.408 sec/batch)\n",
      "step 2400,loss=0.95(249.4 examples/sec;0.401 sec/batch)\n",
      "step 2500,loss=1.06(277.0 examples/sec;0.361 sec/batch)\n",
      "step 2600,loss=0.86(254.5 examples/sec;0.393 sec/batch)\n",
      "step 2700,loss=1.22(236.5 examples/sec;0.423 sec/batch)\n",
      "step 2800,loss=1.10(278.5 examples/sec;0.359 sec/batch)\n",
      "step 2900,loss=1.00(267.4 examples/sec;0.374 sec/batch)\n",
      "step 3000,loss=1.13(253.8 examples/sec;0.394 sec/batch)\n",
      "step 3100,loss=1.05(245.2 examples/sec;0.408 sec/batch)\n",
      "step 3200,loss=0.96(200.5 examples/sec;0.499 sec/batch)\n",
      "step 3300,loss=0.99(273.2 examples/sec;0.366 sec/batch)\n",
      "step 3400,loss=1.14(251.3 examples/sec;0.398 sec/batch)\n",
      "step 3500,loss=0.87(255.1 examples/sec;0.392 sec/batch)\n",
      "step 3600,loss=1.15(242.8 examples/sec;0.412 sec/batch)\n",
      "step 3700,loss=0.93(248.2 examples/sec;0.403 sec/batch)\n",
      "step 3800,loss=0.99(265.3 examples/sec;0.377 sec/batch)\n",
      "step 3900,loss=1.06(260.4 examples/sec;0.384 sec/batch)\n",
      "accuracy = 71.850%\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node input_producer_1/input_producer_1_EnqueueMany}} = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](input_producer_1, input_producer_1/RandomShuffle)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "Exception in thread QueueRunnerThread-input_producer_1-input_producer_1/input_producer_1_EnqueueMany:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node input_producer_1/input_producer_1_EnqueueMany}} = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](input_producer_1, input_producer_1/RandomShuffle)]]\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node input_producer/input_producer_EnqueueMany}} = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](input_producer, input_producer/RandomShuffle)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "ERROR:tensorflow:Exception in QueueRunner: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-input_producer-input_producer/input_producer_EnqueueMany:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node input_producer/input_producer_EnqueueMany}} = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](input_producer, input_producer/RandomShuffle)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-batch/fifo_queue-batch/fifo_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node batch/fifo_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](batch/fifo_queue, per_image_standardization_1, Cast_2)]]\n",
      "\n",
      "Exception in thread QueueRunnerThread-shuffle_batch/random_shuffle_queue-shuffle_batch/random_shuffle_queue_enqueue:\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 916, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\threading.py\", line 864, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\training\\queue_runner_impl.py\", line 257, in _run\n",
      "    enqueue_callable()\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1257, in _single_operation_run\n",
      "    self._call_tf_sessionrun(None, {}, [], target_list, None)\n",
      "  File \"E:\\AISTUDYING\\anaconda3\\envs\\tensorflow\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1407, in _call_tf_sessionrun\n",
      "    run_metadata)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled\n",
      "\t [[{{node shuffle_batch/random_shuffle_queue_enqueue}} = QueueEnqueueV2[Tcomponents=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](shuffle_batch/random_shuffle_queue, per_image_standardization, Cast)]]\n",
      "\n"
     ]
    }
   ],
   "source": [
    "def variable_with_weight_loss(shape,stddev,w1):\n",
    "    var=tf.Variable(tf.truncated_normal(shape,stddev=stddev))\n",
    "    if w1 is not None:\n",
    "        weights_loss=tf.multiply(tf.nn.l2_loss(var),w1,name=\"weights_loss\")\n",
    "        tf.add_to_collection(\"losses\",weights_loss)\n",
    "    return var\n",
    "\n",
    "#使用上一个文件里面已经定义好的文件序列读取函数读取训练数据文件和测试数据从文件.\n",
    "#其中训练数据文件进行数据增强处理，测试数据文件不进行数据增强处理\n",
    "images_train,labels_train=Data.inputs(data_dir=data_dir,batch_size=batch_size,distorted=True)\n",
    "images_test,labels_test=Data.inputs(data_dir=data_dir,batch_size=batch_size,distorted=None)\n",
    "\n",
    "#创建x和y_两个placeholder，用于在训练或评估时提供输入的数据和对应的标签值。\n",
    "#要注意的是，由于以后定义全连接网络的时候用到了batch_size，所以x中，第一个参数不应该是None，而应该是batch_size\n",
    "x=tf.placeholder(tf.float32,[batch_size,24,24,3])\n",
    "y_=tf.placeholder(tf.int32,[batch_size])\n",
    "\n",
    "#创建第一个卷积层 shape=(kh,kw,ci,co)\n",
    "kernel1=variable_with_weight_loss(shape=[5,5,3,64],stddev=5e-2,w1=0.0)\n",
    "conv1=tf.nn.conv2d(x,kernel1,[1,1,1,1],padding=\"SAME\")\n",
    "bias1=tf.Variable(tf.constant(0.0,shape=[64]))\n",
    "relu1=tf.nn.relu(tf.nn.bias_add(conv1,bias1))\n",
    "pool1=tf.nn.max_pool(relu1,ksize=[1,3,3,1],strides=[1,2,2,1],padding=\"SAME\")\n",
    "\n",
    "#创建第二个卷积层\n",
    "kernel2=variable_with_weight_loss(shape=[5,5,64,64],stddev=5e-2,w1=0.0)\n",
    "conv2=tf.nn.conv2d(pool1,kernel2,[1,1,1,1],padding=\"SAME\")\n",
    "bias2=tf.Variable(tf.constant(0.1,shape=[64]))\n",
    "relu2=tf.nn.relu(tf.nn.bias_add(conv2,bias2))\n",
    "pool2=tf.nn.max_pool(relu2,ksize=[1,3,3,1],strides=[1,2,2,1],padding=\"SAME\")\n",
    "\n",
    "#因为要进行全连接层的操作，所以这里使用tf.reshape()函数将pool2输出变成一维向量，并使用get_shape()函数获取扁平化之后的长度\n",
    "reshape=tf.reshape(pool2,[batch_size,-1])    #这里面的-1代表将pool2的三维结构拉直为一维结构\n",
    "dim=reshape.get_shape()[1].value             #get_shape()[1].value表示获取reshape之后的第二个维度的值\n",
    "\n",
    "#建立第一个全连接层\n",
    "weight1=variable_with_weight_loss(shape=[dim,384],stddev=0.04,w1=0.004)\n",
    "fc_bias1=tf.Variable(tf.constant(0.1,shape=[384]))\n",
    "fc_1=tf.nn.relu(tf.matmul(reshape,weight1)+fc_bias1)\n",
    "\n",
    "#建立第二个全连接层\n",
    "weight2=variable_with_weight_loss(shape=[384,192],stddev=0.04,w1=0.004)\n",
    "fc_bias2=tf.Variable(tf.constant(0.1,shape=[192]))\n",
    "local4=tf.nn.relu(tf.matmul(fc_1,weight2)+fc_bias2)\n",
    "\n",
    "#建立第三个全连接层\n",
    "weight3=variable_with_weight_loss(shape=[192,10],stddev=1 / 192.0,w1=0.0)\n",
    "fc_bias3=tf.Variable(tf.constant(0.1,shape=[10]))\n",
    "result=tf.add(tf.matmul(local4,weight3),fc_bias3)\n",
    "\n",
    "#计算损失，包括权重参数的正则化损失和交叉熵损失\n",
    "cross_entropy=tf.nn.sparse_softmax_cross_entropy_with_logits(logits=result,labels=tf.cast(y_,tf.int64))\n",
    "\n",
    "weights_with_l2_loss=tf.add_n(tf.get_collection(\"losses\"))\n",
    "loss=tf.reduce_mean(cross_entropy)+weights_with_l2_loss\n",
    "\n",
    "train_op=tf.train.AdamOptimizer(1e-3).minimize(loss)\n",
    "\n",
    "#函数tf.nn.in_top_k()用来计算输出结果中top k的准确率，函数默认的k值是1，即top 1的准确率，也就是输出分类准确率最高时的数值\n",
    "top_k_op=tf.nn.in_top_k(result,y_,1)\n",
    "\n",
    "init_op=tf.global_variables_initializer()\n",
    "with tf.Session() as sess:\n",
    "    sess.run(init_op)\n",
    "    #启动线程操作，这是因为之前数据增强的时候使用train.shuffle_batch()函数的时候通过参数num_threads()配置了16个线程用于组织batch的操作\n",
    "    tf.train.start_queue_runners()      \n",
    "\n",
    "#每隔100step会计算并展示当前的loss、每秒钟能训练的样本数量、以及训练一个batch数据所花费的时间\n",
    "    for step in range (max_steps):\n",
    "        start_time=time.time()\n",
    "        image_batch,label_batch=sess.run([images_train,labels_train])\n",
    "        _,loss_value=sess.run([train_op,loss],feed_dict={x:image_batch,y_:label_batch})\n",
    "        duration=time.time() - start_time\n",
    "\n",
    "        if step % 100 == 0:\n",
    "            examples_per_sec=batch_size / duration\n",
    "            sec_per_batch=float(duration)\n",
    "            print(\"step %d,loss=%.2f(%.1f examples/sec;%.3f sec/batch)\"%(step,loss_value,examples_per_sec,sec_per_batch))\n",
    "\n",
    "#计算最终的正确率\n",
    "    num_batch=int(math.ceil(num_examples_for_eval/batch_size))  #math.ceil()函数用于求整\n",
    "    true_count=0\n",
    "    total_sample_count=num_batch * batch_size\n",
    "\n",
    "    #在一个for循环里面统计所有预测正确的样例个数\n",
    "    for j in range(num_batch):\n",
    "        image_batch,label_batch=sess.run([images_test,labels_test])\n",
    "        predictions=sess.run([top_k_op],feed_dict={x:image_batch,y_:label_batch})\n",
    "        true_count += np.sum(predictions)\n",
    "\n",
    "    #打印正确率信息\n",
    "    print(\"accuracy = %.3f%%\"%((true_count/total_sample_count) * 100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64a585ce",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
